name: backend_mercadinho
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  shelf: ^1.3.1
  shelf_router: ^1.1.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
